steps:
  # This step builds the container image.
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/github.com/leanwahby/cld_run11:$SHORT_SHA'
      - '.'

  # This step pushes the image to Container Registry
  # The PROJECT_ID and SHORT_SHA variables are automatically
  # replaced by Cloud Build.
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/github.com/leanwahby/cld_run11:$SHORT_SHA'

    # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'crowdfunding-backend-staging'
      - '--image'
      - 'gcr.io/$PROJECT_ID/github.com/leanwahby/cld_run11:$SHORT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/github.com/leanwahby/cld_run11:$SHORT_SHA'