version: '3'

volumes:
  data-volume:
    
services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_cont1
    volumes:
      - .:/nest-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGODB_HOST: mongodb

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin1
      MONGO_INITDB_ROOT_PASSWORD: admin1





# docker-compose up
# docker-compose up -d
# docker-compose up --build
# docker-compose down
# docker exec -it docker-mongo-1 mongosh -u admin -p admin // to run mongosh inside mongo container + auth info