version: '3'

volumes:
  data-volume:

services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_cont1
    volumes:
      - .:/nest-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development






# docker-compose up
# docker-compose up -d
# docker-compose up --build
# docker-compose down
# docker exec -it docker-mongo-1 mongosh -u admin -p admin // to run mongosh inside mongo container + auth info